# SPDX-FileCopyrightText: 2022 Comcast Cable Communications Management, LLC
# SPDX-License-Identifier: Apache-2.0

name: 'Sonarcloud Project Configuration Action'
description: 'Provide a simple way to automate sonarcloud projects.'
branding:
  icon: archive
  color: 'green'
inputs:
  create-missing-project:
    description: 'Create a project in Sonarcloud if one is missing, defaults to true'
    required: false
    default: true

  sonarcloud-org:
    description: 'The Sonarcloud organization name if you have set it to something other than the github org name.'
    required: false
    default: ''

  analysis-mode:
    description: 'Set the analysis mode to one of: cloud, ci or unchanged (default)'
    required: false
    default: unchanged

  sonar-token:
    description: 'The Sonarcloud token used for auth.'
    required: true

runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        API_URL='https://sonarcloud.io/api'
        owner='${{ github.repository_owner }}'
        sowner='${{ inputs.sonarcloud-org }}'
        repo='${{ github.event.repository.name }}'
        repoid='${{ github.event.repository.id }}'
        project="${owner}_${repo}"
        SONAR_TOKEN='${{ inputs.sonar-token }}'
        mode='${{ inputs.analysis-mode }}'

        if [[ "" == "$sowner" ]]; then
          sowner='${{ github.repository_owner }}'
        fi

        if [[ ${{ inputs.create-missing-project }} == "true" ]]; then
          count=`curl -s -f -H "Authorization: Bearer $SONAR_TOKEN" \
                      "${API_URL}/projects/search" \
                      -d "organization=$sowner&projects=${project}" \
                      | jq ".paging.total"`
          if [[ "$count" == "0" ]]; then
            echo "Adding project '$project' to sonarcloud."
            # The way it "should work" based on their documentation.
            #curl -s -f -H "Authorization: Bearer $SONAR_TOKEN" \
            #    -X POST "${API_URL}/projects/create" \
            #    -d "project=${project}&organization=${sowner}&name=${repo}"

            # The way the site makes it work.  It may change.
            curl -s -f -H "Authorization: Bearer $SONAR_TOKEN" \
                -X POST "${API_URL}/alm_integration/provision_projects"
                -d "installationKeys=${owner}/${repo}|${repoid}&organization=${sowner}"
            curl -s -f -H "Authorization: Bearer $SONAR_TOKEN" \
                "${API_URL}/autoscan/eligibility?autoEnable=true&projectKey=${project}"
            if [[ "${mode}" -ne "ci" && "${mode}" -ne "cloud" ]]; then
              mode="cloud"
            fi
          fi
        fi

        if [[ ${{ inputs.analysis-mode }} == "ci" ]]; then
          echo "Setting analysis-mode to ci driven."

          curl -s -f -H "Authorization: Bearer $SONAR_TOKEN" \
               -X POST "${API_URL}/autoscan/activation" \
               -d "enable=false&projectKey=${project}"
        elif [[ ${{ inputs.analysis-mode }} == "cloud" ]]; then
          echo "Setting analysis-mode to cloud driven."

          curl -s -f -H "Authorization: Bearer $SONAR_TOKEN" \
               -X POST "${API_URL}/autoscan/activation" \
               -d "enable=true&projectKey=${project}"
        fi
        echo "Configuration complete."
